-- MySQL Script generated by MySQL Workbench
-- Tue May 12 06:40:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `system` ;

-- -----------------------------------------------------
-- Schema system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `system` DEFAULT CHARACTER SET utf8 ;
USE `system` ;

-- -----------------------------------------------------
-- Table `system`.`mssw_file_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_file_resource` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_file_resource` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `host` VARCHAR(64) NULL DEFAULT NULL,
  `fulll_path` VARCHAR(512) NOT NULL,
  `disabled` INT(11) NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `file_res_fk_operator_id_2_sys_user_idx` (`operator_id` ASC),
  CONSTRAINT `file_res_fk_operator_id_2_sys_user`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process` (
  `id` INT(11) NOT NULL,
  `fk_program_id` INT(11) NOT NULL,
  `fk_program_config_id` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `processor_id` INT(11) NULL DEFAULT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `finish_time` DATETIME NULL DEFAULT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `proc_fk_program_id_2_program_idx` (`fk_program_id` ASC),
  INDEX `proc_fk_program_config_id_2_program_config_idx` (`fk_program_config_id` ASC),
  CONSTRAINT `proc_fk_program_config_id_2_program_config`
    FOREIGN KEY (`fk_program_config_id`)
    REFERENCES `system`.`mssw_program_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proc_fk_program_id_2_program`
    FOREIGN KEY (`fk_program_id`)
    REFERENCES `system`.`mssw_program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_input`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_input` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_input` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `index` INT(11) NOT NULL DEFAULT 0,
  `fk_process_id` INT(11) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_process_id_UNIQUE` (`fk_process_id` ASC),
  UNIQUE INDEX `index_UNIQUE` (`index` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_input_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_input_value` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_input_value` (
  `id` INT(11) NOT NULL,
  `fk_process_model_input_id` INT(11) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `index` INT(11) NOT NULL,
  `data_type` INT(11) NOT NULL,
  `v1` VARCHAR(64) NULL DEFAULT NULL,
  `v2` VARCHAR(64) NULL DEFAULT NULL,
  `v3` VARCHAR(512) NULL DEFAULT NULL COMMENT 'Put json config/list here.',
  PRIMARY KEY (`id`),
  INDEX `proc_model_input_v_fk_proc_model_input_id_2_model_input_idx` (`fk_process_model_input_id` ASC),
  CONSTRAINT `proc_model_input_v_fk_proc_model_input_id_2_model_input`
    FOREIGN KEY (`fk_process_model_input_id`)
    REFERENCES `system`.`mssw_process_model_input` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_log` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `index` INT(11) NOT NULL DEFAULT 0,
  `fk_process_id` INT(11) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_process_id_UNIQUE` (`fk_process_id` ASC),
  UNIQUE INDEX `index_UNIQUE` (`index` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_log_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_log_value` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_log_value` (
  `id` INT(11) NOT NULL,
  `fk_process_model_log_id` INT(11) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `index` INT(11) NOT NULL,
  `data_type` INT(11) NOT NULL,
  `v1` VARCHAR(64) NULL DEFAULT NULL,
  `v2` VARCHAR(64) NULL DEFAULT NULL,
  `v3` VARCHAR(512) NULL DEFAULT NULL COMMENT 'Put json config/list here.',
  PRIMARY KEY (`id`),
  INDEX `proc_model_log_v_fk_proc_model_log_id_2_model_log_idx` (`fk_process_model_log_id` ASC),
  CONSTRAINT `proc_model_log_v_fk_proc_model_log_id_2_model_log`
    FOREIGN KEY (`fk_process_model_log_id`)
    REFERENCES `system`.`mssw_process_model_log` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_output`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_output` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_output` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `index` INT(11) NOT NULL DEFAULT 0,
  `fk_process_id` INT(11) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_process_id_UNIQUE` (`fk_process_id` ASC),
  UNIQUE INDEX `index_UNIQUE` (`index` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_output_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_output_value` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_output_value` (
  `id` INT(11) NOT NULL,
  `fk_process_model_output_id` INT(11) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `index` INT(11) NOT NULL,
  `data_type` INT(11) NOT NULL,
  `v1` VARCHAR(64) NULL DEFAULT NULL,
  `v2` VARCHAR(64) NULL DEFAULT NULL,
  `v3` VARCHAR(512) NULL DEFAULT NULL COMMENT 'Put json config/list here.',
  PRIMARY KEY (`id`),
  INDEX `proc_model_output_v_fk_proc_model_output_id_2_model_output_idx` (`fk_process_model_output_id` ASC),
  CONSTRAINT `proc_model_output_v_fk_proc_model_output_id_2_model_output`
    FOREIGN KEY (`fk_process_model_output_id`)
    REFERENCES `system`.`mssw_process_model_output` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_parameter` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_parameter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `index` INT(11) NOT NULL DEFAULT 0,
  `fk_process_id` INT(11) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_process_id_UNIQUE` (`fk_process_id` ASC),
  UNIQUE INDEX `index_UNIQUE` (`index` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_model_parameter_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_model_parameter_value` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_model_parameter_value` (
  `id` INT(11) NOT NULL,
  `fk_process_model_parameter_id` INT(11) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `index` INT(11) NOT NULL,
  `data_type` INT(11) NOT NULL,
  `v1` VARCHAR(64) NULL DEFAULT NULL,
  `v2` VARCHAR(64) NULL DEFAULT NULL,
  `v3` VARCHAR(512) NULL DEFAULT NULL COMMENT 'Put json config/list here.',
  PRIMARY KEY (`id`),
  INDEX `proc_model_param_v_fk_proc_model_param_id_2_model_param_idx` (`fk_process_model_parameter_id` ASC),
  CONSTRAINT `proc_model_param_v_fk_proc_model_param_id_2_model_param`
    FOREIGN KEY (`fk_process_model_parameter_id`)
    REFERENCES `system`.`mssw_process_model_parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_process_record_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_process_record_access` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_process_record_access` (
  `id` INT(11) NOT NULL,
  `fk_process_id` INT(11) NOT NULL,
  `target_type` INT(11) NOT NULL,
  `target_id` INT(11) NOT NULL,
  `disabled` INT(11) NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `proc_rcd_ca_fk_process_id_2_process_idx` (`fk_process_id` ASC),
  INDEX `proc_rcd_ca_fk_operator_id_2_sys_user_idx` (`operator_id` ASC),
  CONSTRAINT `proc_rcd_ca_fk_operator_id_2_sys_user`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `proc_rcd_ca_fk_process_id_2_process`
    FOREIGN KEY (`fk_process_id`)
    REFERENCES `system`.`mssw_process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_program` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_program` (
  `id` INT(11) NOT NULL,
  `fk_utility_id` INT(11) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `fk_provider_employee_id` INT(11) NULL DEFAULT NULL,
  `fk_parent_program_id` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `operator_id` INT(11) NULL DEFAULT NULL COMMENT 'User ID.',
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `disabled` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_ultility_id_utility_idx` (`fk_utility_id` ASC),
  INDEX `fk_provider_employee_id_sys_employee_idx` (`fk_provider_employee_id` ASC),
  INDEX `fk_parent_program_id_program_idx` (`fk_parent_program_id` ASC),
  INDEX `fk_operator_id_idx` (`operator_id` ASC),
  CONSTRAINT `fk_operator_id`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parent_program_id_program`
    FOREIGN KEY (`fk_parent_program_id`)
    REFERENCES `system`.`mssw_program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provider_employee_id_sys_employee`
    FOREIGN KEY (`fk_provider_employee_id`)
    REFERENCES `system`.`sys_employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ultility_id_utility`
    FOREIGN KEY (`fk_utility_id`)
    REFERENCES `system`.`mssw_utility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_program_activation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_program_activation` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_program_activation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_program_id` INT(11) NOT NULL,
  `fk_dict_activate_type` INT(11) NOT NULL,
  `is_active` INT(11) NOT NULL DEFAULT 1,
  `note` VARCHAR(45) NULL DEFAULT NULL,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_program_id_program_idx` (`fk_program_id` ASC),
  INDEX `program_active_fk_dict_activate_type_2_pub_dict_idx` (`fk_dict_activate_type` ASC),
  INDEX `program_active_fk_operator_id_2_sys_user_idx` (`operator_id` ASC),
  CONSTRAINT `program_active_fk_dict_activate_type_2_pub_dict`
    FOREIGN KEY (`fk_dict_activate_type`)
    REFERENCES `system`.`pub_dict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `program_active_fk_operator_id_2_sys_user`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `program_active_fk_program_id_2_program`
    FOREIGN KEY (`fk_program_id`)
    REFERENCES `system`.`mssw_program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_program_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_program_config` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_program_config` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `fk_program_id` INT(11) NOT NULL,
  `fk_dict_program_cfg_type` INT(11) NOT NULL COMMENT '1: json string\\n2: config file',
  `config_value` VARCHAR(2048) NULL DEFAULT NULL COMMENT 'Type 1: json string;\\nType 2: file path with host address;',
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `disabled` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `porgram_cfg_fk_operator_id_2_sys_user_idx` (`operator_id` ASC),
  INDEX `porgram_cfg_fk_program_id_2_program_idx` (`fk_program_id` ASC),
  INDEX `porgram_cfg_fk_dict_program_cfg_type_2_pub_dict_idx` (`fk_dict_program_cfg_type` ASC),
  CONSTRAINT `fk_operator_id_sys_user`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_id_program`
    FOREIGN KEY (`fk_program_id`)
    REFERENCES `system`.`mssw_program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `porgram_cfg_fk_dict_program_cfg_type_2_pub_dict`
    FOREIGN KEY (`fk_dict_program_cfg_type`)
    REFERENCES `system`.`pub_dict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `porgram_cfg_fk_operator_id_2_sys_user`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `porgram_cfg_fk_program_id_2_program`
    FOREIGN KEY (`fk_program_id`)
    REFERENCES `system`.`mssw_program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_program_config_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_program_config_access` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_program_config_access` (
  `id` INT(11) NOT NULL,
  `fk_program_config_id` INT(11) NOT NULL,
  `target_type` INT(11) NOT NULL COMMENT '1: target_id => User ID\\n2: target_id => Department ID',
  `target_id` INT(11) NULL DEFAULT NULL,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `disabled` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_config_id_program_config_idx` (`fk_program_config_id` ASC),
  INDEX `prog_cfg_ca_fk_operator_id_2_sys_user_idx` (`operator_id` ASC),
  CONSTRAINT `fk_program_config_id_program_config`
    FOREIGN KEY (`fk_program_config_id`)
    REFERENCES `system`.`mssw_program_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prog_cfg_ca_fk_operator_id_2_sys_user`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`sys_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prog_cfg_ca_fk_program_config_id_2_program_config`
    FOREIGN KEY (`fk_program_config_id`)
    REFERENCES `system`.`mssw_program_config` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`mssw_utility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`mssw_utility` ;

CREATE TABLE IF NOT EXISTS `system`.`mssw_utility` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `fk_dict_utility_main_group_id` INT(11) NOT NULL,
  `fk_dict_utility_sub_group_id` INT(11) NOT NULL,
  `disabled` INT(11) NOT NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dict_utility_main_group_id_pub_dict_idx` (`fk_dict_utility_main_group_id` ASC),
  INDEX `utility_fk_dict_sub_group_id_2_pub_dict_idx` (`fk_dict_utility_main_group_id` ASC, `fk_dict_utility_sub_group_id` ASC),
  INDEX `utility_fk_dict_utility_sub_group_id_2_pub_dict_idx` (`fk_dict_utility_sub_group_id` ASC),
  INDEX `utility_fk_operator_id_2_pub_dict_idx` (`operator_id` ASC),
  CONSTRAINT `utility_fk_dict_utility_main_group_id_2_pub_dict`
    FOREIGN KEY (`fk_dict_utility_main_group_id`)
    REFERENCES `system`.`pub_dict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `utility_fk_dict_utility_sub_group_id_2_pub_dict`
    FOREIGN KEY (`fk_dict_utility_sub_group_id`)
    REFERENCES `system`.`pub_dict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `utility_fk_operator_id_2_pub_dict`
    FOREIGN KEY (`operator_id`)
    REFERENCES `system`.`pub_dict` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`pub_dict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`pub_dict` ;

CREATE TABLE IF NOT EXISTS `system`.`pub_dict` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `disabled` INT(11) NOT NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `note` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`sys_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`sys_company` ;

CREATE TABLE IF NOT EXISTS `system`.`sys_company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  `disabled` INT(11) NOT NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`sys_department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`sys_department` ;

CREATE TABLE IF NOT EXISTS `system`.`sys_department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  `fk_sys_company_id` INT(11) NULL DEFAULT NULL,
  `disabled` INT(4) NOT NULL DEFAULT 0,
  `operator_id` VARCHAR(45) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_sys_company_id_idx` (`fk_sys_company_id` ASC),
  CONSTRAINT `fk_sys_company_id_4_sys_department`
    FOREIGN KEY (`fk_sys_company_id`)
    REFERENCES `system`.`sys_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`sys_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`sys_employee` ;

CREATE TABLE IF NOT EXISTS `system`.`sys_employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `note` VARCHAR(200) NULL DEFAULT NULL,
  `fk_sys_department_id` INT(11) NULL DEFAULT NULL,
  `disabled` INT(11) NOT NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_sys_department_id_4_sys_employee_idx` (`fk_sys_department_id` ASC),
  CONSTRAINT `fk_sys_department_id_4_sys_employee`
    FOREIGN KEY (`fk_sys_department_id`)
    REFERENCES `system`.`sys_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `system`.`sys_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `system`.`sys_user` ;

CREATE TABLE IF NOT EXISTS `system`.`sys_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NULL DEFAULT NULL,
  `fk_sys_employee_id` INT(11) NULL DEFAULT NULL,
  `disabled` INT(11) NOT NULL DEFAULT 0,
  `operator_id` INT(11) NULL DEFAULT NULL,
  `operate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_sys_employee_id_4_sys_user_idx` (`fk_sys_employee_id` ASC),
  CONSTRAINT `fk_sys_employee_id_4_sys_user`
    FOREIGN KEY (`fk_sys_employee_id`)
    REFERENCES `system`.`sys_employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
